### ISSUE TITLE
Set ArtNet Subnet and Universe 

### ISSUE THREAD

**Issue by folny** [claudeheintz/LXDMXWiFi_Library#1]
Hi

Can you please suggest how I define instance Universe - 1 and Subnet - 1, Because I am not entirely sure how can I do thanks.

https://github.com/claudeheintz/LXDMXWiFi_Library/blob/master/examples/WiFi2DMX/WiFi2DMX.ino

void loop() {
  uint8_t good_dmx = interface->readDMXPacket(wUDP);

  if ( good_dmx ) {
     for (int i = 1; i <= interface->numberOfSlots(); i++) {
        dmx_output->setSlot(i , interface->getSlot(i));
     }
     blinkLED();
  }
}

**Comment by claudeheintz** [comment]
Hi,
 
The example allows for either sACN or Art-Net.  You want to change line 38:
 
38|  uint8_t use_sacn = 0;
 
to use Art-Net. 
 
The generic LXDMXWiFi class uses a single value for universe although 
sACN and Art-Net treat this a little differently.  Art-Net has the 
first universe number as zero.  The 8 bit universe number is divided 
so that the upper 4 bits are the subnet and the lower 4 bits are the 
universe.  When you create an instance of LXWiFiArtNet it defaults to 
universe zero, subnet zero.  You can use the setUniverse() method to 
change this:
 
85|  } else {
86|     interface = new LXWiFiArtNet(WiFi.localIP(), WiFi.subnetMask());
87|     use_multicast = 0;
88|     interface->setUniverse(0x11); //add this line to set subnet 
1, universe 1
89|  }
 
I hope this answers your question. 
 
-Claude Heintz

On Thu, 17 Dec 2015 13:15:06 -0800, folny  wrote:

       Hi
Can you please suggest how I define instance Universe - 1 and Subnet - 
1, Because I am not entirely sure how can I do thanks
#include
#include
#include
#include
#include
#include
const char* ssid = "ESP2DMX";
const char* pwd = "***";
uint8_t make_access_point = 1;
uint8_t chan = 2;
uint8_t use_sacn = 1;
uint8_t use_multicast = 1;
// dmx protocol interface for parsing packets (created in setup)
LXDMXWiFi* interface;
// LX8266DMXOutput instance for DMX output using UART1/GPIO2
LX8266DMXOutput* dmx_output = new LX8266DMXOutput();
// An EthernetUDP instance to let us send and receive UDP packets
WiFiUDP wUDP;
uint8_t led_state = 0;
void blinkLED() {
if ( led_state ) {
digitalWrite(BUILTIN_LED, HIGH);
led_state = 0;
} else {
digitalWrite(BUILTIN_LED, LOW);
led_state = 1;
}
}
void setup() {
Serialbegin(112500);
SerialsetDebugOutput(1); //use uart0 for debugging
pinMode(BUILTIN_LED, OUTPUT);
if ( make_access_point ) {
WiFimode(WIFI_AP);
WiFisoftAP(ssid);
WiFisoftAPConfig(IPAddress(10,110,115,10), IPAddress(10,1,1,1), 
IPAddress(255,0,0,0));
} else {
WiFimode(WIFI_STA);
WiFibegin(ssid,pwd);
WiFiconfig(IPAddress(10,110,115,15), IPAddress(192,168,1,1), 
IPAddress(255,0,0,0));

while (WiFistatus() != WL_CONNECTED) {
  delay(100);
  blinkLED();
}

}
if ( use_sacn ) { // Initialize Interface
interface = new LXWiFiSACN();
} else {
interface = new LXWiFiArtNet(WiFilocalIP(), WiFisubnetMask());
use_multicast = 0;
}
if ( use_multicast ) { // Start listening for UDP on port
if ( make_access_point ) {
wUDPbeginMulticast(WiFisoftAPIP(), IPAddress(239,255,0,1), 
interface->dmxPort());
} else {
wUDPbeginMulticast(WiFilocalIP(), IPAddress(239,255,0,1), 
interface->dmxPort());
}
} else {
wUDPbegin(interface->dmxPort());
}
//announce presence via Art-Net Poll Reply
if ( ! use_sacn ) {
((LXWiFiArtNet*)interface)->send_art_poll_reply(wUDP);
}
dmx_output->start();
Serialprintln("\nsetup complete");
blinkLED();
}
/************************************************************************
The main loop checks for and reads packets from UDP ethernet socket
connection When a packet is recieved, it is checked to see if
it is valid Art-Net and the art DMXReceived function is called, sending
the DMX values to the output
*************************************************************************/
void loop() {
uint8_t good_dmx = interface->readDMXPacket(wUDP);
if ( good_dmx ) {
for (int i = 1; i numberOfSlots(); i++) {
dmx_output->setSlot(i , interface->getSlot(i));
}
blinkLED();
}
}
—
Reply to this email directly or view it on GitHub. 

   *

-----------------------------------------------------------------
If you prefer not to receive e-mail from Claude Heintz Design,
reply to this message with REMOVE as the subject line. 
Claude Heintz Design, PO Box 8787, Madison, WI 53708

**Comment by claudeheintz** [comment]
The example allows for either sACN or Art-Net.  You want to change line 38:

```c
38|  uint8_t use_sacn = 0;
```
to use Art-Net.
 
The generic LXDMXWiFi class uses a single value for universe although
sACN and Art-Net treat this a little differently.  Art-Net has the
first universe number as zero.  The 8 bit universe number is divided
so that the upper 4 bits are the subnet and the lower 4 bits are the
universe.  When you create an instance of LXWiFiArtNet it defaults to
universe zero, subnet zero.  You can use the setUniverse() method to
change this:

```c
85|  } else {
86|     interface = new LXWiFiArtNet(WiFi.localIP(), WiFi.subnetMask());
87|     use_multicast = 0;
88|     interface->setUniverse(0x11); //add this line to set subnet
1, universe 1
89|  }
```

**Comment by folny** [comment]
Thanks works great will be good if in the future you add some more example of your libraries :-)
