### ISSUE TITLE
bool DMXwifiConfig::artnetMode(void) 

### ISSUE THREAD

**Issue by ririfonfon** [claudeheintz/LXDMXWiFi_Library#10]
hello claude, i have some problem with esp32-dmx_rdm.
I would like to convert my entry dmx to artnet.
I do not understand : ligne 138 to LXDMXWIFIConfig.cpp
bool DMXwifiConfig::artnetMode(void) {
	return ( ( _wifi_config->protocol_flags & SACN_MODE ) == 0 );
}
i tried to change it on:
return ( _wifi_config->protocol_flags & ARTNET_MODE ) ;

but it does not work. still no artnet on the network.

**Comment by claudeheintz** [comment]
I think you want to modify void DMXwifiConfig::initConfig(void) instead.  The config class is designed to hold settings that can be edited over the network using the config utility.  If you are allowing your sketch to use the default config, edit initConfig for your preferred settings specifically:

77] _wifi_config->protocol_flags = MULTICAST_MODE | INPUT_TO_NETWORK_MODE;

and 

96] _wifi_config->input_address = IPAddress(10,255,255,255);

Set the appropriate flag bits in _wifi_config->protocol_flags rather than altering the function that returns their meaning.
