### ISSUE TITLE
esp-dmx configuration utility 

### ISSUE THREAD

**Issue by ririfonfon** [claudeheintz/LXDMXWiFi_Library#11]
hello claude,
i followed your instructions.i managed to connect with esp-dmx configuration utility
I had to make a mistake because since I upload.impossible to reconnect to esp32 .I have therefore taken your example esp32-dmx-rdm and load in the sp.
but still nothing .esp-dmx configuration utility finds nothing.
the serial monitor:

ands Jun 8 2016 00:22:57

rst: 0x10 (RTCWDT_RTC_RESET), boot: 0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP: 0xee
clk_drv: 0x00, q_drv: 0x00, d_drv: 0x00, cs0_drv: 0x00, hd_drv: 0x00, wp_drv: 0x00
mode: DIO, clock div: 1
load: 0x3fff0010, len: 4
Load: 0x3fff0014, len: 572
load: 0x40078000, len: 0
Load: 0x40078000, len: 9880
entry 0x400789d8

config read OK.
AP_MODE ESP-DMX-WiFi created access point at 10.110.115.10 accessPoint SSID ESP-DMX-WiFi,
wifi started 0.0.0.0
starting DMX input
interfaces created, setup complete.
number of tasks is 13

.
the status led (pin 19) flashes well when I come back from the dmx

still no artnet on are network.

how should i do to be able to find esp with esp-dmx configuration utility?

thank you
richard

**Comment by claudeheintz** [comment]
The most likely reasons you lost contact with the ESP-32 and the config utility can't locate it are connectivity issues.  You aren't logged into the same WiFi network, both with the ESP-32 and your computer.  Or, the ESP-32 can't connect to the WiFi network you specified in the configuration.  Or, you specified a static IP address that is on a different subnet than the ones that the config utility searches to find ESP-DMX nodes.

Once you have uploaded a WiFi/DMX configuration, it is saved to persistent memory.  On ESP-32, this is not reset when re-uploading the sketch.  You can force the sketch into loading its default configuration (which is set to be an access point--unless you edited DMXwifiConfig::initConfig )

 38] #define STARTUP_MODE_PIN 18 
...
351] if ( digitalRead(STARTUP_MODE_PIN) == 0 ) {
352]    DMXWiFiConfig.initConfig();
353] }

With other microcontrollers, you can pass digitalRead(STARTUP_MODE_PIN) as the parameter to DMXWiFiConfig.begin(1); on line 348.  But, with the ESP-32 this doesn't work.  So, lines 351 to 353 reset the config struct using initConfig().

Wiring pin 18 to ground temporarily while starting the sketch should cause initConfig() to be called and the ESP-32 will become a wireless access point.  You can then connect your computer to this access point and use the config utility to edit the settings.

In order to use multicast sACN, you'll need to connect the ESP-32 to a WiFi network.  The ESP-32 does not seem to support multicast when in AccessPoint mode.  You can edit the input address to match the IP address of your computer (when connected to the ESP-32's access point).  This will allow you to unicast sACN to your computer.

**Comment by claudeheintz** [comment]
The other important thing to note is that if you have set the mode to input, the ESP will be sending to the network and not listening.  This means that to configure it with the utility, you have to put it into default mode by holding pin 18 low when it starts up.

**Comment by ririfonfon** [comment]
thank you very much.
it works .
the mistake I made was:
DMXInput to net: 10.255.255.255 Art-Net
it works with DMXInput to net: 10.110.115.255 Art-Net
Congratulations for your work
