### ISSUE TITLE
Add another ports

### ISSUE THREAD

**Issue by folny** [claudeheintz/LXDMXWiFi_Library#2]
Hi

Please can you tell me how I could add another port to this library, therefore, that I would need to operate more than 512 channels thanks.

**Comment by claudeheintz** [comment]
I'm not sure that the ESP8266 has the bandwidth to handle 2 universes at full DMX speed.  It may be able to receive the packets.  But what you do with the DMX data will also cost processor power.  For example, I don't think it would be up to trying to push out two separate DMX universes,even though theoretically possible using the two UARTs.  An ESP 8266 is so inexpensive that you might be better off using two separate ESP8266s, one for each universe.

To directly answer your question, the library as written does not support this.  You would need to modify it so that the ArtNet or sACN classes could read a packet from an external buffer.  Then, you would create an instance for each universe and pass the packet data to the one that corresponded to the universe that the packet was addressed to.  (or pass it to the first and if it did not accept it, pass it to the second)

sACN multicast for multiple universes would require a completely separate UDP objects and I'm not sure that is supported.

**Comment by folny** [comment]
I would like to control using your ArtNet library more ws2812 pixels as in this project https://github.com/madsci1016/ESPixelStick I think it might work but I'm not really sure how I should adjust library.

**Comment by claudeheintz** [comment]
The library has an update so that LXWiFiArtNet and LXWiFiSACN objects can use an external buffer for UDP packets (meaning they can share the same data).  There's a new example included for receiving two universes which seems to work (at least with Art-Net).

**Comment by folny** [comment]
Hi

It seems that adding additional Universe works well, I'm still trying to add a port in "replyBuffer [173] = 2; // number of ports" and make it work from port 1 is 0 Universe, and port 2  Universe 1 You can even add this feature to your art poll reply ? thanks.

**Comment by claudeheintz** [comment]
The library has been modified to expose the array of bytes used to send Art-Net Poll Reply packets.  This allows customization when multiple instances are used to receive more than one universe.  The 2 Universe example shows how this can be accomplished.

**Comment by folny** [comment]
Hi

Thanks, I've tested it and it works great.

**Comment by claudeheintz** [comment]
I'm glad its helpful to you.  If you make something cool with it, send 
me a picture. 
 
-Claude Heintz

On Wed, 27 Jan 2016 09:43:22 -0800, folny  wrote:

       Hi
Thanks, I've tested it and it works great. 
—
Reply to this email directly or view it on GitHub. 

   *

-----------------------------------------------------------------
If you prefer not to receive e-mail from Claude Heintz Design,
reply to this message with REMOVE as the subject line. 
Claude Heintz Design, PO Box 8787, Madison, WI 53708
