### ISSUE TITLE
Artnet node not found in AP Mode

### ISSUE THREAD

**Issue by Andreadj** [claudeheintz/LXDMXWiFi_Library#25]
Hi Claude, 
sorry, I know, I'm a pain in the ass... 
I'm trying "Osram DMX WiFi controller" App to drive my Led light with your library with ESP32. To work you should Poll the Artnet node. When connected to a local network (static mode) Artnet node is found and I can drive my light but in AP mode Artnet node is not found or found as 0.0.0.0 IP Address and I can't control the light.
Is this correct? There's a way to solve this?
I found that also with a PC software (Chamsys for PC) in AP mode the Artnet node found is 0.0.0.0
Knowing in advance my AP IP Address maybe I can set the Artnet node IP Address?

**Comment by claudeheintz** [comment]
Hi,

I don't know specifically what the issue is.  The WiFiDMX library responds to Art-Net polls using the IPAddress supplied:

artNetInterface = new LXWiFiArtNet(WiFi.localIP(), WiFi.subnetMask());

You can check to make sure WiFi is initialized and has a WiFi.localIP() before the artnetinterface is initialized.  If WiFi is not initialized it probably returns 0 for WiFi.localIP() which would explain why the Art-Net poll reply would indicate a 0.0.0.0 address.

You can also use a tool like wireshark to look at the actual poll reply and see what address is being sent.

I hope this helps.

​​​​​​​-Claude Heintz
 



On Fri, 28 Oct 2022 08:42:56 -0700, Andreadj ***@***.***> wrote:
 
 

Hi Claude,
sorry, I know, I'm a pain in the ass...
I'm trying "Osram DMX WiFi controller" App to drive my Led light with your library with ESP32. To work you should Poll the Artnet node. When connected to a local network (static mode) Artnet node is found and I can drive my light but in AP mode Artnet node is not found or found as 0.0.0.0 IP Address and I can't control the light.
Is this correct? There's a way to solve this?
I found that also with a PC software (Chamsys for PC) in AP mode the Artnet node found is 0.0.0.0

**Comment by claudeheintz** [comment]
WiFi.localIP() seems to always return 0.0.0.0 in AP mode.  The "ESP32-DMX_rdm" example has been updated to manually keep the local_ip_address and subnet and pass them to the Art-Net constructor.  This results in the poll reply containing the correct address, not 0.0.0.0
 



On Wed, 02 Nov 2022 09:07:26 -0700, Andreadj ***@***.***> wrote:
 
 

Hi Claude,
I think this should be a problem related to "DMXWiFiConfig.apIPAddress()" and "WiFi.localIP()". I also tried your example "ESP32-DMX_rdm" and I have same problem. You can also see it on the serial monitor:
"AP_MODE ESP-DMX-WiFiXcreated access point at 10.110.115.10 accessPoint SSID ESP-DMX-WiFiX, wifi started 0.0.0.0"

**Comment by Andreadj** [comment]
> WiFi.localIP() seems to always return 0.0.0.0 in AP mode.  The "ESP32-DMX_rdm" example has been updated to manually keep the local_ip_address and subnet and pass them to the Art-Net constructor.  This results in the poll reply containing the correct address, not 0.0.0.0   On Wed, 02 Nov 2022 09:07:26 -0700, Andreadj ***@***.***> wrote:     Hi Claude, I think this should be a problem related to "DMXWiFiConfig.apIPAddress()" and "WiFi.localIP()". I also tried your example "ESP32-DMX_rdm" and I have same problem. You can also see it on the serial monitor: "AP_MODE ESP-DMX-WiFiXcreated access point at 10.110.115.10 accessPoint SSID ESP-DMX-WiFiX, wifi started 0.0.0.0" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Hi Claude,
are you sure? look at the picture taken from software:
[https://drive.google.com/file/d/1DqQjI4d4rXhJFd_91uk-ih-oLARLzf0m/view?usp=share_link](https://drive.google.com/file/d/1DqQjI4d4rXhJFd_91uk-ih-oLARLzf0m/view?usp=share_link)
That program used to control lights shows Artnet nodes.
I also tried this App [https://apps.apple.com/it/app/osram-dmx-wi-fi-controller/id577852124](https://apps.apple.com/it/app/osram-dmx-wi-fi-controller/id577852124) and it's not able to find Artnet node:
[https://drive.google.com/file/d/1s1tOE6YhJZpUs8oYP6XnldG02RI3g_-I/view?usp=share_link](https://drive.google.com/file/d/1s1tOE6YhJZpUs8oYP6XnldG02RI3g_-I/view?usp=share_link)

**Comment by claudeheintz** [comment]
DMXWorkshop is the gold standard, made by Artistic License (who invented Art-Net).

The thing is that not all software relies on the IP address passed in the Art-Net Poll Reply.  Some software uses the IPAddress that sent the ArtPollReply packet.  LXConsole does this which is why I thought discovery of the demo example was working.  I didn't realize that the address in the ArtPollReply was 0.0.0.0.

Regardless, with the newly revised ESP32-DMX_rdm demo, the correct IPAddress is included in the poll reply message.  This was verified using Wireshark to examine the actual network packet.  I think you may need to use Wireshark to see what is actually being sent on the network.  There could be an issue with the broadcast of the ArtPoll which would involve a mismatch of the subnet mask.  It could be that the phone app broadcasts to 255.255.255.255 instead of 192.168.4.255 (or whatever the broadcast address is for your scheme).  I'm not sure ESP32 will receive traffic sent to 255.255.255.255.  I seem to remember an issue with it and some broadcast addresses not working.

**Comment by Andreadj** [comment]
I will check. Thanks Claude!
